GET https://localhost:7102/api/wishlist
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5YWQ2NDQwNC0xYWJmLTQ3ZjEtODE4OC03YTcyM2E5MzM3NDUiLCJ1bmlxdWVfbmFtZSI6IlRlc3QzIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDQ5OTkxODUsImV4cCI6MTcwNTYwMzk4NSwiaWF0IjoxNzA0OTk5MTg1LCJpc3MiOiJodHRwczovL21vdmllc2FwaXdlYnRlc3QuYXp1cmV3ZWJzaXRlcy5uZXQifQ.8nA9xve0fS0bGD28N63Ldp1mRXoC9r_YBu-O4WQxKIorPCe6HSBWXjQ2rbCaD2OsDa6PoX7-n5FAU4apmTJpPw
Content-Type: application/json

{
  "text": "Pew-pew",
  "movieId": "6fd87021-ee33-4e3c-8626-220a7023b403"
}

###

PUT https://localhost:7102/api/Comment/d652aacd-88d8-46ac-a908-2de0c85a23ad
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJlMzdlYjA2NC05OTdjLTQwNzEtOWNkOS1hNzRkOGZmNzM3MGUiLCJ1bmlxdWVfbmFtZSI6IlRlc3QzIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDQyOTE5NzMsImV4cCI6MTcwNDg5Njc3MywiaWF0IjoxNzA0MjkxOTczLCJpc3MiOiJsb2NhbGhvc3QifQ.ZXMMKzj7Ak_ieZ6uymprSXnQhafVgozoTtZtOye65L3f1Gnicuv7EFVhpWVX8-HJDP0ZwAIcsyhr5wqr7lXKXQ
Content-Type: application/json

{
  "text": "Pew-pew-pew",
  "movieId": "d652aacd-88d8-46ac-a908-2de0c85a23ad"
}


###

DELETE https://localhost:7102/api/Comment/d652aacd-88d8-46ac-a908-2de0c85a23ad
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJlMzdlYjA2NC05OTdjLTQwNzEtOWNkOS1hNzRkOGZmNzM3MGUiLCJ1bmlxdWVfbmFtZSI6IlRlc3QzIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDQyOTE5NzMsImV4cCI6MTcwNDg5Njc3MywiaWF0IjoxNzA0MjkxOTczLCJpc3MiOiJsb2NhbGhvc3QifQ.ZXMMKzj7Ak_ieZ6uymprSXnQhafVgozoTtZtOye65L3f1Gnicuv7EFVhpWVX8-HJDP0ZwAIcsyhr5wqr7lXKXQ
