POST https://localhost:7102/api/ignores/8e7651e3-dfa8-4d41-a0ef-197b07c7bd6b
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5YWQ2NDQwNC0xYWJmLTQ3ZjEtODE4OC03YTcyM2E5MzM3NDUiLCJ1bmlxdWVfbmFtZSI6IlRlc3QzIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDQ0NDc5MDksImV4cCI6MTcwNTA1MjcwOSwiaWF0IjoxNzA0NDQ3OTA5LCJpc3MiOiJsb2NhbGhvc3QifQ.NK5SalO1aPTSMMZ9Xkiez9JrZqKjUZMPKwufBWAd9jbDZXtc4KYXQlrZxwZCiziw9XH6p7ITRXGDqG4peMTcSw
###

DELETE https://localhost:7102/api/ignores/f70065b6-b425-4faa-8daa-e3977dcae01f
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJlMzdlYjA2NC05OTdjLTQwNzEtOWNkOS1hNzRkOGZmNzM3MGUiLCJ1bmlxdWVfbmFtZSI6IlRlc3QzIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDQzMTQ1OTcsImV4cCI6MTcwNDkxOTM5NywiaWF0IjoxNzA0MzE0NTk3LCJpc3MiOiJsb2NhbGhvc3QifQ.fqTmxCt0T-WiCofRZARKaqmiMrbR7vRO5UqjDzKF7pD_2FPX35SZn8S1NBRc2TvESE36pdo2Kv044SQQWS5FPQ

