GET https://localhost:7102/api/movie

###

GET https://localhost:7102/api/movies/abc1eb6d-bb6a-4bca-ba63-79a65a16086c

###

GET https://localhost:7102/api/movies?sortOrder=Descending

###

GET https://localhost:7102/api/movies?SortBy=title&SortOrder=Ascending

###

POST https://localhost:7102/api/movies
Content-Type: application/json

{
    "title": "aac",
    "inTheaters": false,
    "minimumAge": 13,
    "releaseDate": "1999-03-31",
    "TrailerUrl": "https://www.youtube.com/watch?v=vKQi3bBA1y8",
    "description": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    "actorIds": []
}

###

DELETE  https://localhost:7102/api/movies/b2bf4718-4349-4b14-a229-e810d21ada59