GET https://localhost:7102/api/movies
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5YWQ2NDQwNC0xYWJmLTQ3ZjEtODE4OC03YTcyM2E5MzM3NDUiLCJ1bmlxdWVfbmFtZSI6IlRlc3QzIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDQ0NDc5MDksImV4cCI6MTcwNTA1MjcwOSwiaWF0IjoxNzA0NDQ3OTA5LCJpc3MiOiJsb2NhbGhvc3QifQ.NK5SalO1aPTSMMZ9Xkiez9JrZqKjUZMPKwufBWAd9jbDZXtc4KYXQlrZxwZCiziw9XH6p7ITRXGDqG4peMTcSw###

GET https://localhost:7102/api/movies?title=mat

###

GET https://localhost:7102/api/movies?SortBy=title&SortOrder=Ascending

###

POST https://localhost:7102/api/movies
Content-Type: application/json

{
    "title": "bac",
    "inTheaters": false,
    "minimumAge": 13,
    "releaseDate": "1999-03-31",
    "TrailerUrl": "https://www.youtube.com/watch?v=vKQi3bBA1y8",
    "description": "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    "actorIds": []
}

###

DELETE  https://localhost:7102/api/movies/b2bf4718-4349-4b14-a229-e810d21ada59