GET https://localhost:7102/api/Watchlist
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkYjAzOTZmZS02YTZlLTQzMTctYWU3Zi1mNTQyYzA4MWI2NWIiLCJ1bmlxdWVfbmFtZSI6IkFkbWluIiwicm9sZSI6IkFkbWluIiwibmJmIjoxNzA1NTIyMTg4LCJleHAiOjE3MDYxMjY5ODgsImlhdCI6MTcwNTUyMjE4OCwiaXNzIjoiaHR0cHM6Ly9tb3ZpZXNhcGl3ZWJ0ZXN0LmF6dXJld2Vic2l0ZXMubmV0In0.F_-MyE_gLy2Jz3uHKRlR1To2gRppHmJRlgde2IePqZtjRow-mNVQA7i6VIdfKkkiQT6Bpe1uZahDglzfYCL1Wg

###

POST https://localhost:7102/api/movie/6fd87021-ee33-4e3c-8626-220a7023b403/favourite
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5YWQ2NDQwNC0xYWJmLTQ3ZjEtODE4OC03YTcyM2E5MzM3NDUiLCJ1bmlxdWVfbmFtZSI6IlRlc3QzIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDQ5OTkxODUsImV4cCI6MTcwNTYwMzk4NSwiaWF0IjoxNzA0OTk5MTg1LCJpc3MiOiJodHRwczovL21vdmllc2FwaXdlYnRlc3QuYXp1cmV3ZWJzaXRlcy5uZXQifQ.8nA9xve0fS0bGD28N63Ldp1mRXoC9r_YBu-O4WQxKIorPCe6HSBWXjQ2rbCaD2OsDa6PoX7-n5FAU4apmTJpPw

###

DELETE https://localhost:7102/api/Watchlist/c2fff9d5-4fed-45f1-96ac-1799f69d03ff
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkODBhNmZiMi0yMWVmLTRkNTktOGQwMS0wNGZiZTIxY2UwMTciLCJ1bmlxdWVfbmFtZSI6IlRlc3QzIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDQyMzM2MzUsImV4cCI6MTcwNDgzODQzNSwiaWF0IjoxNzA0MjMzNjM1LCJpc3MiOiJsb2NhbGhvc3QifQ.YxovGylMs5MMuPrBT-wEYXOZMiCt75UrClQakeu5Jt1uQSu59Tw2b2EIwCJK7tprG3viCh12wXgPo8oWNYfSQQ
