GET https://localhost:7102/api/Watchlist
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkODBhNmZiMi0yMWVmLTRkNTktOGQwMS0wNGZiZTIxY2UwMTciLCJ1bmlxdWVfbmFtZSI6IlRlc3QzIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDQyMzM2MzUsImV4cCI6MTcwNDgzODQzNSwiaWF0IjoxNzA0MjMzNjM1LCJpc3MiOiJsb2NhbGhvc3QifQ.YxovGylMs5MMuPrBT-wEYXOZMiCt75UrClQakeu5Jt1uQSu59Tw2b2EIwCJK7tprG3viCh12wXgPo8oWNYfSQQ

###

POST https://localhost:7102/api/Watchlist/2dda7f5d-f9d9-460a-86a7-27c45129075e
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkODBhNmZiMi0yMWVmLTRkNTktOGQwMS0wNGZiZTIxY2UwMTciLCJ1bmlxdWVfbmFtZSI6IlRlc3QzIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDQyMzM2MzUsImV4cCI6MTcwNDgzODQzNSwiaWF0IjoxNzA0MjMzNjM1LCJpc3MiOiJsb2NhbGhvc3QifQ.YxovGylMs5MMuPrBT-wEYXOZMiCt75UrClQakeu5Jt1uQSu59Tw2b2EIwCJK7tprG3viCh12wXgPo8oWNYfSQQ

###

DELETE https://localhost:7102/api/Watchlist/e05e1189-3cfe-48d6-9609-a87665387e12
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJkODBhNmZiMi0yMWVmLTRkNTktOGQwMS0wNGZiZTIxY2UwMTciLCJ1bmlxdWVfbmFtZSI6IlRlc3QzIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3MDQyMzM2MzUsImV4cCI6MTcwNDgzODQzNSwiaWF0IjoxNzA0MjMzNjM1LCJpc3MiOiJsb2NhbGhvc3QifQ.YxovGylMs5MMuPrBT-wEYXOZMiCt75UrClQakeu5Jt1uQSu59Tw2b2EIwCJK7tprG3viCh12wXgPo8oWNYfSQQ
